version: "2"

networks:
  app-tier:
    driver: bridge

services:

  phpfpm-5.6:
    image: 'bitnami/php-fpm:5.6'
    networks:
      - app-tier
    volumes:
      - ./images/nginx-5.6/www:/data/www/

  phpfpm-7.1:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
    volumes:
      - ./images/nginx-7.1/www:/data/www/

  nginx-5.6:
    image: 'bitnami/nginx:latest'
    # depends_on:
    #   - phpfpm
    networks:
      - app-tier
    ports:
      # - '80:80'
      - '7000:7000'
      # - '443:443'
    volumes:
      - ./images/nginx-5.6/config/hello.conf:/bitnami/nginx/conf/vhosts/hello.conf
      - ./images/nginx-5.6/www:/data/www/
      - ./logs/nginx-7.1:/opt/bitnami/nginx/logs
  nginx-7.1:
    image: 'bitnami/nginx:latest'
    # depends_on:
    #   - phpfpm
    networks:
      - app-tier
    ports:
      # - '80:80'
      - '7001:7001'
      # - '443:443'
    volumes:
      - ./images/nginx-7.1/config/hello.conf:/bitnami/nginx/conf/vhosts/hello.conf
      - ./logs/nginx-7.1:/opt/bitnami/nginx/logs

  mysql:
    image: mysql
    networks:
      - app-tier
    ports:
      - "7706:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      # MYSQL_DATABASE: "test"
      # MYSQL_USER: "root"
      # MYSQL_PASSWORD: "123456"
    volumes:
      - ./images/mysql/data:/var/lib/mysql
